version: '3'
services:
  db:
    image: postgres:12
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    build: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    tty: true

volumes:
  postgres-data: